version: '3'
services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command: "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - 9100:9100
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager
    volumes:
      - ./alertmanager:/etc/alertmanager
    command: "--config.file=/etc/alertmanager/config.yml"
    ports:
      - 9093:9093
    restart: unless-stopped

  alertmanager-discord:
    image: benjojo/alertmanager-discord
    ports:
      - 9094:9094
    environment:
      - DISCORD_WEBHOOK=$DISCORD_WEBHOOK
    restart: unless-stopped
