version: '3'
services:
  prometheus:
    image: prom/prometheus:v2.43.0
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=365d"
    ports:
      - 9090:9090
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:v1.5.0
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.systemd'
      - '--collector.processes'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc|run|var|boot)($$|/)'
    ports:
      - 9100:9100
    restart: unless-stopped

  grafana:
    image: grafana/grafana:9.4.7
    volumes:
      - grafana:/var/lib/grafana
    ports:
      - 3000:3000
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:v0.25.0
    volumes:
      - ./alertmanager:/etc/alertmanager
      - alertmanager:/data
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/data/"
    ports:
      - 9093:9093
    restart: unless-stopped

  alertmanager-discord:
    image: benjojo/alertmanager-discord@sha256:7d27cd8494b269fe592cf6a9d7f6bdf14ac628bba34c381dc43cf533eaa95158
    ports:
      - 9094:9094
    environment:
      - DISCORD_WEBHOOK=$DISCORD_WEBHOOK
    restart: unless-stopped

volumes:
  prometheus:
  grafana:
  alertmanager:
