# This is the main input for unit testing.
# Only this file is passed as command line argument.

rule_files:
    - alert.rules

evaluation_interval: 1m

tests:
    # Test 1.
    - interval: 1m
      # Series data.
      input_series:
          - series: 'up{job="prometheus", instance="localhost:9090"}'
            values: '0 0 0 0 0 0 0 0 0 0 0 0 0 0 0'
          - series: 'up{job="node_exporter", instance="localhost:9100"}'
            values: '1+0x6 0 0 0 0 0 0 0 0' # 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0
          - series: 'node_filesystem_avail_bytes{mountpoint="/home/data/std-36"}'
            values: '5000+0x6 900+0x8'
          - series: 'node_filesystem_size_bytes{mountpoint="/home/data/std-36"}'
            values: '10000+0x14'
          - series: 'smartmon_offline_uncorrectable_raw_value{instance="node-exporter:9100"}'
            values: '0+0x6 1+0x8'
          - series: 'smartmon_current_pending_sector_raw_value{instance="node-exporter:9100"}'
            values: '0+0x6 1+0x8'
          - series: 'smartmon_reallocated_sector_ct_raw_value{instance="node-exporter:9100"}'
            values: '0+0x6 1+0x8'
      # Unit test for alerting rules.
      alert_rule_test:
          - eval_time: 10m
            alertname: instance_down
            exp_alerts:
                # Alert 1.
                - exp_labels:
                      severity: critical
                      instance: localhost:9090
                      job: prometheus
                  exp_annotations:
                      summary: "Instance localhost:9090 down"
                      description: "localhost:9090 of job prometheus has been down for more than 5 minutes."

          - eval_time: 10m
            alertname: SMART_Offline_uncorrectable
            exp_alerts:
                # Alert 1.
                - exp_labels:
                      severity: critical
                  exp_annotations:
                      summary: "SMART: Offline uncorrectable"
                      description: "Offline uncorrectable sector found"

          - eval_time: 10m
            alertname: SMART_Current_pending_sector
            exp_alerts:
                # Alert 1.
                - exp_labels:
                      severity: critical
                  exp_annotations:
                      summary: "SMART: Current pending sector"
                      description: "Pending sector found"

          - eval_time: 10m
            alertname: SMART_Reallocated_sector_count
            exp_alerts:
                # Alert 1.
                - exp_labels:
                      severity: critical
                  exp_annotations:
                      summary: "SMART: Reallocated sector count"
                      description: "Reallocated sector found"

          - eval_time: 10m
            alertname: std-36_free_space_low
            exp_alerts:
                # Alert 1.
                - exp_labels:
                      mountpoint: /home/data/std-36
                      severity: critical
                  exp_annotations:
                      summary: "std-36 free space low"
                      description: "std-36 disk space used: 91 %"
